# Class 1: Basics and Array Manipulation
## 1. What is NumPy? NumPy (Numerical Python) is a library in Python used for working with arrays (like lists but faster and more efficient). It is essential for data analysis, data engineering, and machine learning because it can handle  large datasets and perform calculations quickly.

# 2. Installing and Importing NumPy
## To install NumPy, run this in your terminal or command prompt

In [1]:
# pip install numpy

## Import Numpy in your code like this

In [2]:
import numpy as np

## We use np as a short name for NumPy.
# 3. Creating Arrays
## Arrays are like lists, but better for mathematical operations. Here's how to create them:



# 1D Array (one row):
## What They Represent:
### A 1D array is like a simple list. It is used to store a sequence of values (e.g., a list of numbers or a single column of data).

## Data storage for single variables:

## Example: Store the age of people in a dataset.

In [3]:
ages = np.array([25, 30, 35, 40])
print(ages)


[25 30 35 40]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)  

[1 2 3 4 5]


# 2D Array (rows and columns):
## What They Represent:
## A 2D array is like a table or matrix with rows and columns. It’s used to store structured data, such as a dataset with multiple features or attributes.

## Use Cases:
## Storing tabular data:

### Example: A dataset with rows as samples and columns as features.

In [5]:
data = np.array([[25, 180, 75],  # Age, Height(cm), Weight(kg)
                [30, 175, 70],
                [35, 165, 60]])
# Define the model
print(data)

[[ 25 180  75]
 [ 30 175  70]
 [ 35 165  60]]


## Matrix operations:

### Used for calculations in linear algebra (e.g., dot product, matrix multiplication).

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3D Array (multiple 2D arrays):
## What They Represent:
### A 3D array is like a stack of 2D arrays or a cube of data. It is used to store datasets with more than two dimensions, such as sequences of images or multi-channel data.

## Use Cases:
## RGB Images (Colored Images):

### A 3D array can represent an image with height, width, and color channels (Red, Green, Blue).

In [8]:
rgb_image = np.array([[[255, 0, 0],  # Red pixel
                        [0, 255, 0],  # Green pixel
                        [0, 0, 255]],  # Blue pixel
                        [[255, 255, 0],  # Yellow pixel
                        [255, 0, 255],  # Magenta pixel
                        [0, 255, 255]]])  # Cyan pixel

In [9]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Create Numpy with Random Numbers


# 1. Random rand()
###  Purpose: Generates random numbers between 0 and 1 (inclusive of 0, but not 1).
###  Distribution: Uniform distribution (all values in the range are equally likely).
###  Input: You can specify the shape of the array.

## Syntax

In [10]:
# np.random.rand(d0, d1, ..., dn)

## Generate a single random number:

In [11]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.80308952 0.58012729 0.57142517 0.54045785]


## Generate a 2D random number:

In [12]:

var1 = np.random.rand(2,3)
print(var1)

print("\nType of array is",type(var1))


[[0.82558963 0.9163352  0.20496278]
 [0.06954524 0.38883543 0.16804827]]

Type of array is <class 'numpy.ndarray'>


## Generate a 3D array of random numbers:

In [25]:

# Create a 3D array with random values between 0 and 1
random_array_3d = np.random.rand(2, 3, 4)

print("Generated 3D Array:")
print(random_array_3d)


Generated 3D Array:
[[[0.62691321 0.32938871 0.0576767  0.61040777]
  [0.15579809 0.45646524 0.77744207 0.49521167]
  [0.21539721 0.69075378 0.78054449 0.17590746]]

 [[0.83930652 0.10116475 0.89948019 0.35175851]
  [0.96276789 0.53987191 0.1055533  0.26988539]
  [0.43788355 0.74836473 0.2360733  0.51441882]]]


## The array contains:
- 2 layers
- Each layer has 3 rows
- Each row has 4 columns

# 2. randn
## Purpose: Generates random numbers that can be (positive or negative), centered around 0.

## Distribution: Standard normal distribution (bell curve) with mean 0 and standard deviation 1.

## Input: You can specify the shape of the array.


## Syntax

In [14]:
# np.random.randn(d0, d1, ..., dn)

## Generate a single random number:

In [31]:

random_number = np.random.randn()
print(random_number)


-0.23323573141688864


## Generate a 1D array of random numbers:

In [52]:
random_array_1d = np.random.randn(5)  # Generates a 1D array with 5 elements
print(random_array_1d)

[ 1.10812203  2.26322888  1.56085133 -0.34293297  0.4675059 ]


## Generate a 2D array of random numbers:

In [17]:

random_array_2d = np.random.randn(3, 4)  # Generates a 3x4 2D array
print(random_array_2d)


[[-0.01781877  1.38543623 -0.34292798 -0.66414045]
 [ 0.89846532 -0.03767833 -1.15057091  1.91569651]
 [-0.34283384  0.76056084  0.1775333  -1.34599254]]


## Generate a 3D array of random numbers:

In [18]:

random_array_3d = np.random.randn(2, 3, 4)  # Generates a 2x3x4 3D array
print(random_array_3d)


[[[ 0.21168362  1.76708124  2.20746739  1.99344246]
  [-0.40149609  0.05795859  0.81015033  0.22083588]
  [ 0.72625523 -0.67151828  1.28996205  0.41069516]]

 [[-2.10612156  0.10238971 -0.85837358 -0.67378235]
  [ 0.36508325  0.34235346 -0.48149224  0.0833184 ]
  [-0.20459806  1.23079857  0.02166554  0.47307987]]]


# 3. ranf
## Purpose: Generates random numbers between 0 and 1 (like rand), but the shape must be handled separately.
## Distribution: Uniform distribution.
## Difference from rand: ranf does not directly accept shape as arguments; instead, use reshaping if needed.

## Syntax

In [19]:
np.random.random(size=None) or np.random.ranf(size=None)

0.8753232399708811

In [20]:
var3 = np.random.ranf(3)
print(var3)

[0.47639198 0.86919448 0.67000822]


## Through a TypeError because of positional argument means here order matter's

In [21]:
var4 = np.random.ranf(2,3)
print(var4)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [53]:
# Here's order matter
var5 = np.random.ranf(6)
print(var5)



var5 = np.random.ranf(6).reshape(2,3)
print(var5)


[0.18355365 0.49344318 0.50913641 0.56890542 0.88886933 0.39053961]
[[0.41676985 0.53670487 0.73566442]
 [0.00982842 0.56446567 0.26386891]]


# 4. randint
## Range: Specify low (inclusive) and high (exclusive).
## Purpose: Generates random integer numbers within a specified range.
## Input: You can also specify the size (shape) of the array.

## Syntax

In [ ]:
# np.random.randint(low, high=None, size=None, dtype=int)

# or

# np.random.randint(min, max,total_values)

In [22]:
var6 = np.random.randint(5, 10, size=(3, 4))  # Generate random integers in range [5, 10) with shape 3x4
print(var6) 

[[8 8 7 9]
 [8 9 9 5]
 [8 6 6 6]]


In [23]:
var0 = np.random.randint(5,20,5)
print(var0)

[16  9 12  8 14]


In [24]:
var7 = np.random.randint(5,8)
print(var7)

6


# Array Attributes
## You can inspect the properties of an array:

# Shape:
## Tells you how many rows and columns the array has.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2,3)

(2, 3)


# Data Type:
## Shows the type of data in the array (e.g., integers, floats).

In [9]:
print(arr.dtype)

int32


# Data Type:
## Shows the type of data in the array (e.g., integers, floats).

In [10]:
print(arr.ndim) # (for 2D array)

2


# Size:

## Tells how many total elements are in the array.

In [11]:
print(arr.size)  

6


## NUMPY: Shape

In [12]:
import numpy as np

var = np.array([[1,2,3,4],[5,6,7,8]])
print("Var:",var)

print("\nShape of var is:",var.shape)



Var: [[1 2 3 4]
 [5 6 7 8]]

Shape of var is: (2, 4)


In [13]:
var1 = np.array([9,8,7,6], ndmin=4)
print(var1)
print(var1.ndim)

print("\nShape of var is:",var1.shape)

[[[[9 8 7 6]]]]
4

Shape of var is: (1, 1, 1, 4)


# Reshape
### using reshape() function converting 1D Array to 2D Array or can also do in others

In [14]:
var2 = np.array([1,2,3,4,5,6])

print("One Dimension Array:",var2)

x = var2.reshape(2,3)
print("\nArray of 2 by 3\n",x)

y = var2.reshape(3,2)
print("\nArray of 3 by 2\n",y)


One Dimension Array: [1 2 3 4 5 6]

Array of 2 by 3
 [[1 2 3]
 [4 5 6]]

Array of 3 by 2
 [[1 2]
 [3 4]
 [5 6]]


## Checking Dimensions

In [15]:
print("Dimension of var2:",var2.ndim)

print("Dimension of x:",x.ndim)

print("Dimension of y:",y.ndim)

Dimension of var2: 1
Dimension of x: 2
Dimension of y: 2


## Converting Array to 1D Array

In [16]:
z = y.reshape(-1)
print(z)

[1 2 3 4 5 6]
